name: ddc_2
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - numpy=1.21.2
  - joblib=1.0.1
  - pandas=1.2.3
  - pip
  - seaborn=0.12.0
  - scikit-learn=1.0.2
  - statsmodels=0.13.2
  - shap=0.40.0
  - unidecode=1.2.0
  - scipy=1.7.1
  - seaborn=0.12.0
  - matplotlib
  - ply=3.11
  - xgboost==1.4.2
  - postgresql=12.9
  - luigi=3.0.3
  - psycopg2=2.9.3
  - jupyter
  - keras=2.10.0
  - pip:
    - pdfminer3k==1.3.2
    - lifelines==0.27.3
    - xlrd==2.0.1
    - openpyxl==3.0.10
    - statsmodels==0.13.5
    - scikit-survival==0.19.0
    - SQLAlchemy==1.4.46
    - torch
    - transformers

